coci_cora:
  lr: 0.001
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  p_e: 0.5
  p_a: 0.0
  tau: 0.4
  num_epochs: 200
  weight_decay: 0.00001

coau_cora:
  lr: 0.001
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  p_e: 0.9
  p_a: 0.1
  tau: 0.4
  num_epochs: 200
  weight_decay: 0.00001